web:
  build: cloudpebble/
  ports:
    - "80:80"
  volumes:
    - "./cloudpebble/:/code"
  links:
    - redis
    - postgres
    - s3
    - qemu
    - ycmd
  environment:
    - DEBUG="yes"
    - RUN_WEB="yes"
    - AWS_ENABLED="yes"
    - PORT=80
    - AWS_S3_FAKE_S3=s3:4569
    - MEDIA_URL=http://localhost:8003/s3/builds.cloudpebble.net/
    - QEMU_URLS=http://localhost:8001/
    - YCM_URLS=http://localhost:8002/
    - PUBLIC_URL=http://localhost/
    - LIBPEBBLE_PROXY=wss://cloudpebble-ws.herokuapp.com/tool
    - PEBBLE_AUTH_URL=https://auth.rebble.io
    - REDIS_URL=redis://redis:6379
    - QEMU_LAUNCH_TIMEOUT=60
    - DOCKER_COMPOSE=yes
celery:
  build: cloudpebble/
  volumes:
    - "./cloudpebble/:/code"
  links:
    - redis
    - postgres
    - s3
  environment:
    - DEBUG="yes"
    - RUN_CELERY="yes"
    - AWS_ENABLED=yes
    - EXPORT_ROOT=http://localhost:8003/s3/export.cloudpebble.net/
    - AWS_S3_FAKE_S3=s3:4569
    - REDIS_URL=redis://redis:6379
qemu:
  build: cloudpebble-qemu-controller/
  volumes:
    - "./cloudpebble-qemu-controller/:/code"
  ports:
    - "8001:80"
ycmd:
  build: cloudpebble-ycmd-proxy/
  volumes:
    - "./cloudpebble-ycmd-proxy/:/code"
  ports:
    - "8002:80"
redis:
  image: redis
postgres:
  image: postgres
  environment:
    POSTGRES_DB: "db"
    POSTGRES_HOST_AUTH_METHOD: "trust"
s3:
  image: mrister/fake-s3
  ports:
    - "8003:4569"
